version: "3"

volumes:
  nginx_storage: {}

services:
  profile-images:
    image: profile-images:latest
    working_dir: /app
    environment:
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT:-5500}
      - HTTP_SERVER_HOST=${HTTP_SERVER_HOST:-0.0.0.0}
      - CATALYST_MAINNET=${CATALYST_MAINNET:-https://peer.decentraland.org}
      - CATALYST_GOERLI=${CATALYST_GOERLI:-https://peer.decentraland.zone}
      - WEARABLES_PREVIEW_URL=${WEARABLES_PREVIEW_URL:-http://localhost:5500/index.html}
    env_file:
      - .env
    volumes:
      - "./node_modules/@dcl/wearable-preview/static-local:/var/www/html"
    expose:
      - "5500"
    restart: always

  nginx:
    container_name: nginx-2
    image: nginx:1.23-alpine
    ports:
      - "81:80"
#      - "444:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./node_modules/@dcl/wearable-preview/static-local/:/usr/share/nginx/html/preview
    restart: always
    depends_on:
      - profile-images
    links:
      - profile-images
